services:

    _defaults:
        autowire: true
        autoconfigure: true

    Syno\Cint\HttpClient:
        public: false

    Syno\Cint\Connect\:
        resource: '../src/Connect/*'

    Syno\Cint\Demand\:
        resource: '../src/Demand/*'